### PR TITLE
Display condition logic and new DSL features: country and rudimentary rollout/experimentation

### LINKED ISSUE #1210: Add user-selected country as an input variable for all displayCondition logic
All dynamic items in the app including the symptom checker should allow using the user-selected country as an input.

### LINKED ISSUE #1211: Add date as input to displayCondition evaluation
All dynamic items in the app including the symptom checker should allow using the current date as an input.

### LINKED ISSUE #1213: A/B testing: Add a cohort value as an input into the displayCondition logic
All dynamic items in the app including the symptom checker should allow using a cohort [0-1000) as input in the displayCondition.  

The cohort can be used to have X% of persons see one view while the rest see another to test the effectiveness of different treatments.

The cohort can be reported as an analytics user value to get close to true A/B testing.

### LINKED ISSUE #1291: Learn Index crashes with more than 4 items

### PR DESCRIPTION
**Pull request by advayDev1**
Display condition logic and new DSL features:
```
ctx_isoCountryCode == 'US' && inExperiment('13,54,93') - Shows something to 3 pct of US folks
ctx_localDays % 7 == 4 - Shows something once every week in user's local time
```

Implemented in Home, Learn, and Symptom Checker

Closes #1210 ; Closes #1211 ; Closes #1213 ; Affects #1209 ; Closes #1291 

TESTED: Android sim on Home/Learn/S-C with test yamls from: https://github.com/WorldHealthOrganization/app/commit/f4f2f124c3a33d1a403aa19d8558f48ae6f8f826

### CODE REVIEW

File: client/flutter/lib/api/display_conditions.dart [hunk 1]
```diff
@@ -1,9 +1,77 @@
...
+      @required this.localDays});
+
+  static final _refDate = DateTime(2020);
+
+  static Future<LogicContext> generate() async {
+    final now = DateTime.now().toUtc();
+    final diff = now.toLocal().difference(_refDate).inDays;
+    return LogicContext(
+      cohort: await UserPreferences().getCohort(),
+      isoCountryCode: await UserPreferences().getCountryIsoCode(),
```
Comment (hspinks) [inline client/flutter/lib/api/display_conditions.dart:34]: Will this be a problem if the expression evaluator attempts to evaluate something that is null?

Comment (advayDev1) [reply client/flutter/lib/api/display_conditions.dart:34]: Null works in the expressions package. 👍
