### PR TITLE
Turn on content loading / remove incorrect content

### LINKED ISSUE #813: Turn on server side access

### PR DESCRIPTION
**Pull request by advayDev1**
For now we'll just get 404s.  But it means that Server side it doesn't need to be done by 5pm.

Closes #813

### CODE REVIEW

File: client/flutter/lib/api/content_loading.dart [hunk 1]
```diff
@@ -6,12 +6,12 @@ import 'package:flutter/material.dart';
 import 'content_bundle.dart';
 
 class ContentLoading {
-  static final networkLoadingEnabled = false;
+  static final networkLoadingEnabled = true;
   static final ContentLoading _singleton = ContentLoading._internal();
 
   // TODO: Real URL
```
Comment (PieterAelse) [inline client/flutter/lib/api/content_loading.dart:12]: Can this `TODO` now be removed? 🙂

Comment (advayDev1) [reply client/flutter/lib/api/content_loading.dart:12]: No, won't remove until confirmed with Bob
