### PR TITLE
Implement Learn page; implement named routing; fix scroll bug; random UI fixes too; switch analytics to named routes

### LINKED ISSUE #1114: Implement Learn Index screen to new design
**The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.**

Design is a WIP, but at least get the visual elements on the screen

<details>
<summary>Rough mock (subject to change)</summary>
Screen Shot 2020-04-22 at 6 08 17 PM
</details>

### LINKED ISSUE #1149: Pages with content shorter than the screen should not scroll
Turns out easier than we thought @davidkaneda ;)

### PR DESCRIPTION
**Pull request by advayDev1**
Implement Learn page; implement named routing; fix scroll bug; random UI fixes too: font sizes in header, header replacement/border color; switch analytics to named routes

Closes #1149
Closes #1114
Partly done #1103
Partly done #1125

Screen Shot 2020-04-28 at 12 00 13 AM

What analytics will look like:
Screen Shot 2020-04-28 at 11 56 38 PM

### CODE REVIEW

File: client/flutter/lib/api/content/schema/index_content.dart [hunk 1]
```diff
@@ -0,0 +1,71 @@
+import 'package:flutter/material.dart';
+import 'package:who_app/api/content/content_bundle.dart';
+import 'package:who_app/api/linking.dart';
+import '../content_loading.dart';
```
Comment (hspinks) [inline client/flutter/lib/api/content/schema/index_content.dart:4]: nit: use the `package:who_app/<path>` syntax instead of relative paths for consistency

File: client/flutter/lib/components/page_scaffold/page_header.dart [hunk 2]
```diff
@@ -5,44 +5,55 @@ import 'package:auto_size_text/auto_size_text.dart';
 class PageHeader extends StatelessWidget {
   final String title;
   final String heroTag;
+  final Color borderColor;
+  final double fontSize;
```
Comment (hspinks) [inline client/flutter/lib/components/page_scaffold/page_header.dart:9]: once #1151 is merged, let's add `TypographyVariant` and then maybe make this more generic with a `TextStyle` instead of only allowing font size override?

```suggestion
  final FontStyle titleStyle;
  final TypographyVariant titleVariant;
```

File: client/flutter/lib/api/content/schema/fact_content.dart [hunk 3]
```diff
@@ -1,5 +1,6 @@
 import 'package:who_app/api/content/content_bundle.dart';
-import 'package:flutter/cupertino.dart';
+import 'dart:ui';
+import 'package:meta/meta.dart';
```
Comment (hspinks) [inline client/flutter/lib/api/content/schema/fact_content.dart:3]: Do we need these imports?

File: client/flutter/lib/api/content/schema/advice_content.dart [hunk 4]
```diff
@@ -1,5 +1,6 @@
 import 'package:who_app/api/content/content_bundle.dart';
-import 'package:flutter/cupertino.dart';
+import 'dart:ui';
+import 'package:meta/meta.dart';
```
Comment (hspinks) [inline client/flutter/lib/api/content/schema/advice_content.dart:3]: Do we need these imports?

File: client/flutter/lib/api/content/schema/question_content.dart [hunk 5]
```diff
@@ -1,5 +1,6 @@
 import 'package:who_app/api/content/content_bundle.dart';
-import 'package:flutter/cupertino.dart';
+import 'dart:ui';
+import 'package:meta/meta.dart';
```
Comment (hspinks) [inline client/flutter/lib/api/content/schema/question_content.dart:3]: Do we need these imports?

File: client/flutter/lib/components/page_scaffold/page_scaffold.dart [hunk 6]
```diff
@@ -14,28 +20,44 @@ class PageScaffold extends StatelessWidget {
...
+    return Container(
+      color: this.color,
+      child: Padding(
+        padding: this.padding,
+        child: Stack(
+          children: <Widget>[
+            CustomScrollView(
+                physics: BouncingScrollPhysics(parent: ClampingScrollPhysics()),
+                slivers: [
+                  ...this.beforeHeader,
```
Comment (hspinks) [inline client/flutter/lib/components/page_scaffold/page_scaffold.dart:44]: I get what you're doing here with the `beforeHeader`, but... on the pages where we have the promo content, is the page title really still a header? I would have thought about those pages as not having a header at all, and the title & promo content just being part of the page `body` (but, as always, open to hearing why that approach is wrong 😄)

File: client/flutter/lib/pages/main_pages/learn_page.dart [hunk 7]
```diff
@@ -1,15 +1,207 @@
...
+  final IndexDataSource dataSource;
+
+  const LearnPage({Key key, @required this.dataSource}) : super(key: key);
+
+  @override
+  _LearnPageState createState() => _LearnPageState();
+}
+
+class _LearnPageState extends State<LearnPage> {
+  final whoBlue = Color(0xFF3D8BCC);
```
Comment (hspinks) [inline client/flutter/lib/pages/main_pages/learn_page.dart:22]: Extract a constant?

File: client/flutter/lib/pages/main_pages/learn_page.dart [hunk 8]
```diff
@@ -1,15 +1,207 @@
...
+  final header =
+      TextStyle(color: Colors.black, fontSize: 24, fontWeight: FontWeight.w800);
+  IndexContent _content;
+
+  static const _bigItemColor = Color(0xCC1694BE);
```
Comment (hspinks) [inline client/flutter/lib/pages/main_pages/learn_page.dart:27]: Extract a constant?

File: client/flutter/lib/pages/main_pages/learn_page.dart [hunk 9]
```diff
@@ -1,15 +1,207 @@
...
   @override
   Widget build(BuildContext context) {
     return PageScaffold(
-      showHeader: false,
-      body: [
-        LearnPageHeader(),
+      disableBackButton: true,
+      headingBorderColor: Color(0x0),
+      heroTag: HeroTags.learn,
+      title: "Learn",
```
Comment (hspinks) [inline client/flutter/lib/pages/main_pages/learn_page.dart:57]: TODO to localize?

File: client/flutter/lib/pages/main_pages/learn_page.dart [hunk 10]
```diff
@@ -1,15 +1,207 @@
...
+      showHeader: _content != null,
+      header: SliverToBoxAdapter(
+          child: Padding(
+              padding:
+                  EdgeInsets.only(left: 16, right: 16, top: 36, bottom: 12),
+              child: PageHeader.buildTitle("Learn", fontSize: 40))),
```
Comment (hspinks) [inline client/flutter/lib/pages/main_pages/learn_page.dart:63]: TODO to localize?

File: client/flutter/lib/pages/question_index.dart [hunk 11]
```diff
@@ -149,7 +151,7 @@ class _QuestionTileState extends State<QuestionTile>
               child: Html(
                 data: widget.questionItem.title,
                 defaultTextStyle: _titleStyle.copyWith(
-                  fontSize: 16 * MediaQuery.of(context).textScaleFactor,
+                  fontSize: 18 * MediaQuery.of(context).textScaleFactor,
```
Comment (hspinks) [inline client/flutter/lib/pages/question_index.dart:154]: I know this was from a prior change, but... shouldn't we remove textScaleFactor? I think this will apply the scale factor twice, no?

Comment (advayDev1) [reply client/flutter/lib/pages/question_index.dart:154]: Html widget does not account for textScaleFactor.

File: client/flutter/lib/api/content/schema/question_content.dart (hunk 5 above)
Comment (advayDev1) [reply client/flutter/lib/api/content/schema/question_content.dart:3]: They are the correct imports.  We were using cupertino as a transitive crutch for this. :)

File: client/flutter/lib/api/content/schema/fact_content.dart (hunk 3 above)
Comment (advayDev1) [reply client/flutter/lib/api/content/schema/fact_content.dart:3]: They are the correct imports.  We were using cupertino as a transitive crutch for this. :)

File: client/flutter/lib/api/content/schema/advice_content.dart (hunk 4 above)
Comment (advayDev1) [reply client/flutter/lib/api/content/schema/advice_content.dart:3]: They are the correct imports.  We were using cupertino as a transitive crutch for this. :)

File: client/flutter/lib/api/content/schema/index_content.dart (hunk 1 above)
Comment (advayDev1) [reply client/flutter/lib/api/content/schema/index_content.dart:4]: fixed in full repo

File: client/flutter/lib/components/page_scaffold/page_header.dart (hunk 2 above)
Comment (advayDev1) [reply client/flutter/lib/components/page_scaffold/page_header.dart:9]: Fixed the size -> style issue for now.  Depending on the merge order, will do variant too.

File: client/flutter/lib/components/page_scaffold/page_scaffold.dart (hunk 6 above)
Comment (advayDev1) [reply client/flutter/lib/components/page_scaffold/page_scaffold.dart:44]: Hmm... it says you hid this comment so not sure if you don't want me to respond?

I think it is a header, semantically (i.e. from an accessibility perspective).

**Comment by advayDev1** [comment]
Thanks @hspinks - ptal.  One open issue to see if you agree with: https://github.com/WorldHealthOrganization/app/pull/1150#discussion_r417622175

File: client/flutter/lib/components/page_scaffold/page_scaffold.dart (hunk 6 above)
Comment (hspinks) [reply client/flutter/lib/components/page_scaffold/page_scaffold.dart:44]: GitHub hid this automatically, it wasn't something I chose - probably GitHub telling me that I was leaving too many comments 😉 

I guess it is hard to tell with the designs not yet finalized what these views might look like and whether those elements will continue to actually be headers, but as they stand right now, they are, and the accessibility argument makes sense to me 👍 

Now I'll mark this as resolved to hide it 😄
