### PR TITLE
Fix: arrow button overflowing (fixes #979)

### LINKED ISSUE #979: Accessibility: arrow button overflowing with large font
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Arrow button is overflowing on small devices with increased accessibility font size:

before 2
before

PR coming

### PR DESCRIPTION
**Pull request by tomgilder**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: #979 
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Fixes #979 - font size overflowing on buttons (see screenshots below)

## Did you add any dependencies?

No.

## How did you test the change?

Manually on iOS simulator

Before
before
After
after

Before
before 2
After
after 2

### CODE REVIEW

File: client/flutter/lib/components/arrow_button.dart [hunk 1]
```diff
@@ -11,15 +11,16 @@ class ArrowButton extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     return FlatButton(
-      shape: StadiumBorder(),
+      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(35)),
```
Comment (britannio) [inline client/flutter/lib/components/arrow_button.dart:14]: isn't `StadiumBorder` the correct shape?

Comment (tomgilder) [reply client/flutter/lib/components/arrow_button.dart:14]: This doesn't change the shape when the text is on one line.

With large text the button turns almost into a circle with `StadiumBorder`, and just looks weird:

Simulator Screen Shot - iPhone 5s - 2020-04-10 at 00 17 40

Comment (britannio) [reply client/flutter/lib/components/arrow_button.dart:14]: Ah, cool.

**Comment by britannio** [comment]
> I love accessibility fixes!

Then you'll love https://github.com/WorldHealthOrganization/app/pull/944
