### PR TITLE
Svg was behind the status bar

### LINKED ISSUE #1340: Get The Latest News Screen Logo is overlapping Mobile Notification Bar
To Reproduce

1. Launch the app on Moto X4 for the first time
2. Tap on Get Started button on the launch screen.
3. User is navigated to  Get the latest news from your community screen
4. Observe the  Logo on top of the screen.

Expected, correct behavior
Logo placing should be correct and it should not overlap the mobile notification menu bar.

Phone/Tablet (please complete the following information):

- Device: [Moto X4]
- OS: [Android 9.0]
- App Version: [0.11.1 + 21]

Additional context
Issue is not observed on my Huawei Honor 7c device having 5.5. inch screen

Screenshots
Get_The_Latest_News_Logo_Placing

---

Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).

- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ x] Issue has descriptive title focused on the feature or problem from the user's perspective

### PR DESCRIPTION
**Pull request by Luccasoli**
There was an excessively large padding at bottom of screen, which prevented the images from being properly sized, and there was a lack of padding for the status bar

Closes #1340 

#### Screenshots
<details> 
<summary>
Before

Screenshot_1590122009
Screenshot_1590122033

After
Screenshot_1590123321
Screenshot_1590123325

</summary>
</details>

#### Did you add any dependencies?
No

#### How did you test the change?
* [ ] iOS Simulator
* [X] Android Emulator
* [ ] iOS Device
* [ ] Android Device
* [ ] `curl` to a dev App Engine server

---

#### Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).

- [ ] REQUIRED: Do you have an Issue **assigned to you** for this PR?
- [X] Provided detailed pull request description and a succinct title
- [X] Tested your changes, especially after any code review iterations.
- [X] Included any relevant screenshots of UI updates.
- [X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [X] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [X] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

### CODE REVIEW

**Comment by Luccasoli** [comment]
> Can't all of this be done more reliably with a SafeArea?

@theswerd It sure would be! But as I am new to this code, I tried to correct it in the simplest possible way.

A better solution could have a larger Container with BoxConstraints.expand(), which would contain a color that would be displayed in these "insecure parts of the screen", and keep the useful part of the screen inside a SafeArea, which would be a child of this larger Container.

What do you think?

**Comment by theswerd** [comment]
Sounds good

**Comment by Luccasoli** [comment]
Screenshot_1591327618
Screenshot_1591327621

Screenshot_1591327866
Screenshot_1591327876

I tried to apply a more responsive approach (which will avoid overflow and also, the image will not be too small)

File: client/flutter/lib/pages/onboarding/country_select_page.dart [hunk 1]
```diff
@@ -21,74 +21,99 @@ class CountrySelectPage extends StatelessWidget {
...
+                        ),
                       ),
-                      child: ThemedText(
-                        'Next',
-                        variant: TypographyVariant.button,
-                        style: TextStyle(
-                          color: CupertinoColors.white,
+                      Padding(
+                        padding: EdgeInsets.only(
+                            left: 36.0, right: 20.0, bottom: 18.0),
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/country_select_page.dart:49]: Add trailing comma
```suggestion
                            left: 36.0, 
                            right: 20.0, 
                            bottom: 18.0,
                          ),
```

File: client/flutter/lib/pages/onboarding/country_select_page.dart [hunk 2]
```diff
@@ -21,74 +21,99 @@ class CountrySelectPage extends StatelessWidget {
...
+                            color: Constants.accentNavyColor,
+                            fontWeight: FontWeight.w800,
+                          ),
                         ),
-                        textAlign: TextAlign.center,
                       ),
-                    ),
+                      Padding(
+                        padding: EdgeInsets.only(
+                            left: 36.0, right: 54.0, bottom: 12.0),
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/country_select_page.dart:61]:
```suggestion
                            left: 36.0, 
                            right: 54.0, 
                            bottom: 12.0,
                          ),
```

Comment (theswerd) [reply client/flutter/lib/pages/onboarding/country_select_page.dart:61]: Add trailing comma

File: client/flutter/lib/pages/onboarding/country_select_page.dart [hunk 3]
```diff
@@ -21,74 +21,99 @@ class CountrySelectPage extends StatelessWidget {
...
+              ),
+              Expanded(
+                  flex: 4,
+                  child: SingleChildScrollView(
+                    child: Column(
+                      crossAxisAlignment: CrossAxisAlignment.stretch,
+                      children: <Widget>[
+                        _buildOpenListRow(),
+                        Padding(
+                          padding: EdgeInsets.fromLTRB(24.0, 32.0, 24.0, 12.0),
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/country_select_page.dart:82]: Add trailing comma
```suggestion
                          padding: EdgeInsets.fromLTRB(
                            24.0, 
                            32.0, 
                            24.0, 
                            12.0,
                          ),
```

File: client/flutter/lib/pages/onboarding/notifications_page.dart [hunk 4]
```diff
@@ -23,90 +23,111 @@ class _NotificationsPageState extends State<NotificationsPage> {
...
+                          left: 36.0,
+                          bottom: 18.0,
+                          top: 10,
                         ),
+                        child: SvgPicture.asset(
+                            'assets/svg/undraw-onboarding-notifications.svg'),
+                      ),
+                      Padding(
+                        padding: EdgeInsets.only(
+                            left: 36.0, right: 20.0, bottom: 18.0),
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/notifications_page.dart:50]:
```suggestion
                            left: 36.0, 
                            right: 20.0, 
                            bottom: 18.0,
                          ),
```
Add trailing comma

File: client/flutter/lib/pages/onboarding/notifications_page.dart [hunk 5]
```diff
@@ -23,90 +23,111 @@ class _NotificationsPageState extends State<NotificationsPage> {
...
-                    )
-                  ],
+                      )
+                    ],
+                  ),
+                ),
+              ),
+              Expanded(
+                flex: 3,
+                child: SingleChildScrollView(
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/notifications_page.dart:81]: This view has two isolated scroll views, which could cause potential usage problems for a user who doesn't want to scroll through the buttons. Possibly one or both should be a Column.

@davidkaneda what is your thought?

File: client/flutter/lib/pages/onboarding/notifications_page.dart [hunk 6]
```diff
@@ -23,90 +23,111 @@ class _NotificationsPageState extends State<NotificationsPage> {
...
-          Expanded(
-            child: Container(
-              alignment: Alignment.bottomLeft,
-              padding: EdgeInsets.only(left: 36.0, bottom: 18.0),
-              child: SvgPicture.asset(
-                  'assets/svg/undraw-onboarding-notifications.svg'),
-            ),
-          ),
-          Column(
+      child: Container(
```
Comment (theswerd) [inline client/flutter/lib/pages/onboarding/notifications_page.dart:26]: I believe since we have a Material with a background color we can delete the container from the heirarchy.

Comment (Luccasoli) [reply client/flutter/lib/pages/onboarding/notifications_page.dart]: you're right, i removed it in my last commit

File: client/flutter/lib/pages/onboarding/notifications_page.dart (hunk 5 above)
Comment (Luccasoli) [reply client/flutter/lib/pages/onboarding/notifications_page.dart]: my concern was the size of the images on older phones / small screens, but in this last commit I tried to control only with the flex widgets

**Comment by Luccasoli** [comment]
Screenshots

2560x1800 xhdpi - Android 9.0
Screenshot_1592702475
Screenshot_1592702482

480x854 hdpi - Android 5.1
Screenshot_1592702486
Screenshot_1592702493

**Comment by Luccasoli** [comment]
Thanks!! :D

**Comment by Luccasoli** [comment]
@theswerd @advayDev1 guys, is this app being developed through any official funding / partnership with the world health organization? Or are we devs doing this on our own? I didn't see this information in the readme and I was curious, thanks anyway :DD

**Comment by advayDev1** [comment]
> @theswerd @advayDev1 guys, is this app being developed through any official funding / partnership with the world health organization? Or are we devs doing this on our own? I didn't see this information in the readme and I was curious, thanks anyway :DD

@luccasoli We are a group of volunteers working with the World Health Organization.  At the moment, we’re working with their staff on finalizing an additional set of features for the initial app release.
