### PR TITLE
Fix share sheet presentation on iPad

### LINKED ISSUE #1020: Share the App doesn't work on iPad
Click Share the App on iPad.
Nothing happens.

### PR DESCRIPTION
**Pull request by cbgrey**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [X ] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here:
- [X ] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [X ] Included any relevant screenshots of UI updates.
- [X ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ X] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [X ] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Fixes #1020 

Share sheet geometry now calculated from context. 

## Did you add any dependencies?

No

## How did you test the change?

Tested in iOS simulators for iPad (7th gen), iPad Pro 12.9", iPad Pro 11" and iPhone 11. 
Tested on physical Android Pixel 4XL

Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-04-15 at 12 48 58

### CODE REVIEW

File: client/flutter/lib/pages/home_page.dart [hunk 1]
```diff
@@ -116,7 +118,9 @@ class HomePage extends StatelessWidget {
                         itemId: null,
                         method: 'Website link');
                     Share.share(
-                        S.of(context).commonWhoAppShareIconButtonDescription);
+                        S.of(context).commonWhoAppShareIconButtonDescription,
+                        sharePositionOrigin: Rect.fromLTWH(0, 0, size.width, size.height / 2),
```
Comment (hspinks) [inline client/flutter/lib/pages/home_page.dart:122]: This isn't necessarily a blocker for this since this does work to fix the issue, but I'd suggest that we use the position of the Share button bar instead of placing this randomly on the screen... it feels a little weird that the tooltip is pointing at nothing on the screen. Some example code for that is [here](https://alligator.io/flutter/share-plugin/#adding-the-share-functionality). I'm fine with merging this as-is and opening a separate ticket to track that, or including that change in this PR
