### PR TITLE
GetStats: Persist the country only on success

### LINKED ISSUE #1858: Wrong Stats are being displayed when internet connectivity is lost and country is changed
1.  Launch the app and complete onboarding journey.
2.  Tap on Stats icon in the footer.
3.  Stats for the selected country is displayed to the user.
4.  Switch of mobile internet.
5.  Go to Settings and and change the country from the dropdown.
6.  Tap on Stats again after changing the country.

Expected Behavior
Previous Country Stats should not be loaded for the changed country

Actual Behavior 
Stats of previously selected country are being displayed for the newly selected country.

 System

- Device: Huawei Honor 7c
- OS: Android 8.0
- App Version: Version 1.0.0-staging(281)

 Additional Context

Another observation is that if we change the country by the search option in the dropdown then this bug doesn't occur, it only happens when we change the country by scrolling the country selector dropdown.

https://user-images.githubusercontent.com/63721227/102717147-706d2d00-4306-11eb-9d45-2a5755048e5d.mp4

Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by matthewblain**
GetStats: Persist the country only on success.
Fixes #1858 

## Screenshots

<details>
<summary>Screenshots</summary>
Add any relevant before/after screenshots here
</details>

## How did you test the change?

- [ ] iOS Simulator
- [ ] iOS Device
- [ ] Android Simulator
- [ ] Android Device
- [ ] `curl` to a dev App Engine server
- [ ] other, please describe

I have not yet tested this! Will do so later today.

## Checklist:

- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

### CODE REVIEW

File: client/lib/api/stats_store.dart [hunk 1]
```diff
@@ -80,8 +80,8 @@ abstract class _StatsStore with Store implements Updateable {
       return;
     }
 
-    countryIsoCode = prefs.countryIsoCode;
-    if (countryIsoCode == null) {
+    var countryToLoad = prefs.countryIsoCode;
+    if (countryToLoad == null) {
```
Comment (brunobowden) [inline client/lib/api/stats_store.dart:84]: How about inline `prefs.countryIsoCode`?
```suggestion
    if (prefs.countryIsoCode == null) {
        caseStatsResponse =
            await service.getCaseStats(isoCountryCode: prefs.countryIsoCode);	        
        _lastUpdateTimestamp = now;
        countryIsoCode = prefs.countryIsoCode;
    }
```

**Comment by brunobowden** [comment]
git precommit checks aren't running so try:
```
flutter format lib/**
```

File: client/lib/api/stats_store.dart (hunk 1 above)
Comment (brunobowden) [reply client/lib/api/stats_store.dart:84]: On second thoughts, the local variable avoids a possible race condition where the country setting was changed

**Review by brunobowden — APPROVED** [review]

**Comment by matthewblain** [comment]
Fixed formatting. Small debuglog and other tweaks.

Tested: Disabled internet / switched country / enabled as per bug. 
The 'stale' data from the old country will remain until the internet connection returns, then will quickly refresh to the selected country.
It would be possible to zero out the data on country change, but I don't know if it's better to show blank data there or 'wrong' data. It is labeled correctly (with the 'old' country) in the UI.

Triage/priority note: without this fix, the problem will resolve itself when the local data expires, either on app restart or 1 hour.

**Review by yukuairoy — APPROVED** [review]

**Comment by Mohit020888** [comment]
> Fixed formatting. Small debuglog and other tweaks.
> 
> Tested: Disabled internet / switched country / enabled as per bug.
> The 'stale' data from the old country will remain until the internet connection returns, then will quickly refresh to the selected country.
> It would be possible to zero out the data on country change, but I don't know if it's better to show blank data there or 'wrong' data. It is labeled correctly (with the 'old' country) in the UI.
> 
> Triage/priority note: without this fix, the problem will resolve itself when the local data expires, either on app restart or 1 hour.

@matthewblain - I think it's better to show blank data suggesting Internet connectivity issues to the user rather than populating wrong data.

**Comment by brunobowden** [comment]
@matthewblain @Mohit020888 - this is somewhat a corner case. I'd rather invest energy in to migrating to Firestore which will handle this situation and many others far better.

**Review by theswerd — APPROVED** [review]
LGTM - should we add an indicator that the network failed?

**Comment by brunobowden** [comment]
@theswerd - I think people generally know when they don’t have an internet connection. I’d rather they invest the effort in migrating to Firestore

**Comment by matthewblain** [comment]
OK I'll merge this now. Agree that this is a corner case, even this fix itself, and firebase is likley to provide a more robust mechanism.

**Comment by Mohit020888** [comment]
@matthewblain @brunobowden - being a tester I can't help myself playing with these corner case scenarios and reporting them but I agree with prioritizing other important tasks which can take care of these issues.
